#!/bin/sh
pyformex --search -- -E '^ *(import|from .* import) ' 2>/dev/null | sed 's/[^:]*://;s/ *//' | sort | uniq | grep -v 'pyformex' | grep -v 'from \.' | awk '{print $2}' | sed 's/,.*//;s/\..*//' | sort | uniq
